### ISSUE TITLE
Conflict with any ScoreBoard Stats

### ISSUE THREAD

**Issue by ClarkHalf** [Proxying/TabManager#21]
For some reason easy scoreboard messes up the order of TabManager.
So I can not put alphabetically the groups in tab (a-z)

**Comment by ClarkHalf** [comment]
@Proxying

**Comment by Proxying** [comment]
If it's only with Easy Scoreboard and not any other scoreboard plugins then you'll have to open a ticket there, or check their configs to see if there are any compatibility settings.

**Comment by ClarkHalf** [comment]
Right

And as for that which appears, Is there any solution?

28.04 13:31:21 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task tabmanager-placeholder-updater owned by Plugin{id=tabmanager, name=TabManager, version=2.1.3-S7.0-MC1.12.2, description=Customize your tab list in Sponge., authors=[Proxying, RandomByte], source=./mods/TabManager-2.1.3-S7.0-MC1.12.2.jar}, but an error occured.
28.04 13:31:21 [Server] INFO java.lang.IllegalStateException: Name is 18 characters long! It must be at most 16.
28.04 13:31:21 [Server] INFO at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.1.12.2.jar:?]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scoreboard.builder.SpongeTeamBuilder.name(SpongeTeamBuilder.java:66) ~[SpongeTeamBuilder.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at uk.co.proxying.tabmanager.utils.ScoreHandler.addPlayerGroupData(ScoreHandler.java:51) ~[ScoreHandler.class:?]
28.04 13:31:21 [Server] INFO at uk.co.proxying.tabmanager.utils.Utilities.updateGroupPlayerName(Utilities.java:63) ~[Utilities.class:?]
28.04 13:31:21 [Server] INFO at uk.co.proxying.tabmanager.utils.Utilities.checkAndUpdateName(Utilities.java:98) ~[Utilities.class:?]
28.04 13:31:21 [Server] INFO at uk.co.proxying.tabmanager.TabManager.lambda$startUpdateTask$4(TabManager.java:456) ~[TabManager.class:?]
28.04 13:31:21 [Server] INFO at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_181]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:404) [SpongeMod.class:1.12.2-2768-7.1.6-RC3616]
28.04 13:31:21 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
28.04 13:31:21 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
28.04 13:31:21 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746) [EventBus.class:?]
28.04 13:31:21 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696) [EventBus.class:?]
28.04 13:31:21 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
28.04 13:31:21 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
28.04 13:31:21 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
28.04 13:31:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by ClarkHalf** [comment]
@Proxying

**Comment by Proxying** [comment]
"Name is 18 characters long! It must be at most 16." Reduce the size of the rank name

**Comment by ClarkHalf** [comment]
But there is no other solution without being this, right? Sorry for the inconvenience.

**Comment by Proxying** [comment]
No, it's a minecraft limitation of 16 characters on the scoreboard.

https://minecraft.gamepedia.com/Scoreboard

**Comment by ClarkHalf** [comment]
Thx proxying <3

**Comment by ClarkHalf** [comment]
I forgot to talk, It's not only with easyscoreboard

**Comment by ClarkHalf** [comment]
@Proxying , It's not only with easyscoreboard, All scoreboards have conflict

**Comment by ClarkHalf** [comment]
@Proxying

**Comment by ClarkHalf** [comment]
@Proxying  Please

**Comment by Proxying** [comment]
No clue, stop spamming.

**Comment by ClarkHalf** [comment]
I'm sorry :/
