### ISSUE TITLE
Header and Footer are not work in the latest version of sponge

### ISSUE THREAD

**Issue by ahdg6** [Proxying/TabManager#23]
I'm using the latest version of sponge,and the Header and Footer are not work
It won't happen in the Sponge version:1.12.2-2838-7.1.7-RC3845
https://github.com/SpongePowered/SpongeCommon/commit/2fde9d092e60c35dc3f70c0e8e8430cc8f9ab747
Forge:1.12.2 - 14.23.5.2838
Sponge:1.12.2-2838-7.1.7-RC3847
[12:58:02] [error] [Sponge]: The Scheduler tried to run the task tabmanager-placeholder-updater owned by Plugin{id=tabmanager, name=TabManager, version=2.1.3-S7.0-MC1.12.2, description=Customize your tab list in Sponge., authors=[Proxying, RandomByte], source=.\mods\TabManager-2.1.3-S7.0-MC1.12.2.jar}, but an error occured.
java.lang.NoClassDefFoundError: org/spongepowered/common/mixin/core/network/play/server/SPacketPlayerListHeaderFooterAccessor
	at org.spongepowered.common.entity.player.tab.SpongeTabList.refreshClientHeaderFooter(SpongeTabList.java:117) ~[SpongeTabList.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.common.entity.player.tab.SpongeTabList.setHeader(SpongeTabList.java:83) ~[SpongeTabList.class:1.12.2-2838-7.1.7-RC3847]
	at uk.co.proxying.tabmanager.utils.Utilities.checkAndUpdateName(Utilities.java:82) ~[Utilities.class:?]
	at uk.co.proxying.tabmanager.TabManager.lambda$startUpdateTask$4(TabManager.java:456) ~[TabManager.class:?]
	at uk.co.proxying.tabmanager.TabManager$$Lambda$2208.0000000016C6E280.run(Unknown Source) ~[?:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.api.scheduler.Task$Builder$$Lambda$434.0000000013EFA460.accept(Unknown Source) ~[?:?]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.common.scheduler.SchedulerBase$$Lambda$576.0000000015F5D6F0.run(Unknown Source) ~[?:?]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.common.scheduler.SchedulerBase$$Lambda$574.00000000165152B0.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_202]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.1.7-RC3847]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:417) [SpongeMod.class:1.12.2-2838-7.1.7-RC3847]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_198_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:752) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:702) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]

**Comment by Kael007** [comment]
++++

**Comment by ahdg6** [comment]
Please fix it,As the sponge is updating,your plugin can't work well https://github.com/SpongePowered/SpongeCommon/commit/2fde9d092e60c35dc3f70c0e8e8430cc8f9ab747
@Proxying

**Comment by Proxying** [comment]
I will not be creating an updated branch for these changes for a little while. I do not know why Sponge implemented breaking changes like this internally for no reason (other than to roleplay?). This was not required by an MC update or Forge update. I'll wait until they decide on what they are doing before I update. If you want to use this, stick to a tested SF.

**Comment by ahdg6** [comment]
It works again
