### ISSUE TITLE
[BUG] Problem with NucleusNicknameService

### ISSUE THREAD

**Issue by poqdavid** [Proxying/TabManager#29]
And we are using 

spongeforge-1.12.2-2838-7.3.0
Nucleus-2.3.2-MC1.12.2-SpongeAPI7.3-plugin
TabManager-2.1.3-S7.0-MC1.12.2

```
[08:03:58] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task tabmanager-placeholder-updater owned by Plugin{id=tabmanager, name=TabManager, version=2.1.3-S7.0-MC1.12.2, description=Customize your tab list in Sponge., authors=[Proxying, RandomByte], source=./mods/TabManager-2.1.3-S7.0-MC1.12.2.jar}, but an error occured.
java.lang.NoClassDefFoundError: io/github/nucleuspowered/nucleus/api/service/NucleusNicknameService
	at uk.co.proxying.tabmanager.TabManager.isUseNicknames(TabManager.java:479) ~[TabManager.class:?]
	at uk.co.proxying.tabmanager.utils.Utilities.updateOtherUsersForPlayer(Utilities.java:135) ~[Utilities.class:?]
	at uk.co.proxying.tabmanager.utils.Utilities.checkAndUpdateName(Utilities.java:80) ~[Utilities.class:?]
	at uk.co.proxying.tabmanager.TabManager.lambda$startUpdateTask$4(TabManager.java:456) ~[TabManager.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:188) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_282]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.3.0]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:441) [SpongeMod.class:1.12.2-2838-7.3.0]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by TitiOnFire** [comment]
Hi,
Use this vesion, I'm recomplit it.

[TabManager-2.1.4-S7.3.0-MC1.12.2.zip](https://github.com/Proxying/TabManager/files/6334823/TabManager-2.1.4-S7.3.0-MC1.12.2.zip)
