### ISSUE TITLE
Error when a player disconnects

### ISSUE THREAD

**Issue by Jay9519** [Proxying/TabManager#4]
Running TabManager 1.0.4
SpongeForge 1.10.2-2281-5.2.0-BETA-2344

getting this error on the console...

[22:53:56] [Server thread/ERROR] [Sponge/]: Could not pass ClientConnectionEvent$Disconnect$Impl to Plugin{id=tabmanager, name=TabManager, version=1.0.4, description=Customize your tab list in Sponge., authors=[Proxying], source=/home/ozserver/ozserver/modded/mods/TabManager-1.0.4.jar}
java.lang.NullPointerException
	at uk.co.proxying.tabmanager.utils.ScoreHandler.removeFromTeam(ScoreHandler.java:73) ~[ScoreHandler.class:?]
	at uk.co.proxying.tabmanager.listeners.PlayerListener.onPlayerLeave(PlayerListener.java:26) ~[PlayerListener.class:?]
	at org.spongepowered.common.event.listener.DisconnectListener_PlayerListener_onPlayerLeave157.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2344]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2344]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2344]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2344]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2344]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2281-5.2.0-BETA-2344]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$zhd000(NetHandlerPlayServer.java:2282) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:802) [me.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:455) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by Proxying** [comment]
Fixed for a while. Sorry regarding delayed response.
